-- SEQUENCE 序列表
DROP TABLE IF EXISTS `SEQUENCE`;
CREATE TABLE `SEQUENCE`
(
  `NAME`      VARCHAR(56) NOT NULL
  COMMENT '序列名称',
  `VALUE`     INT(11)     NOT NULL
  COMMENT '当前值',
  `INCREMENT` INT(2)      NOT NULL
  COMMENT '步长',
  PRIMARY KEY (`NAME`)
);
ALTER TABLE `SEQUENCE`
  COMMENT = '序列表';

-- CURRVAL 当前序列值
DROP FUNCTION IF EXISTS `CURRVAL`;
DELIMITER //
CREATE FUNCTION `CURRVAL`(SEQ_NAME VARCHAR(50))
  RETURNS INT(11) READS SQL DATA DETERMINISTIC
  BEGIN
    DECLARE CURRVAL INTEGER;
    SET CURRVAL = 0;
    SELECT `VALUE`
    INTO CURRVAL
    FROM `SEQUENCE`
    WHERE `NAME` = SEQ_NAME;
    RETURN CURRVAL;
  END//
DELIMITER ;

-- NEXTVAL 下一个序列值
DROP FUNCTION IF EXISTS `NEXTVAL`;
DELIMITER //
CREATE FUNCTION `NEXTVAL`(SEQ_NAME VARCHAR(50))
  RETURNS INT(11) DETERMINISTIC
  BEGIN
    UPDATE `SEQUENCE`
    SET `VALUE` = `VALUE` + `INCREMENT`
    WHERE `NAME` = SEQ_NAME;
    RETURN CURRVAL(SEQ_NAME);
  END//
DELIMITER ;